---
title: "경험적 사례연구, 코스피 대상승 시대의 시초인가?"
author: "김희수"
date: "2018년 11월 3일"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(xlsx)
```

## 1.배경
오늘따라 코스피가 미친듯이 상승하였다.

과연 대세상승의 시초인가 궁금하여 3.5%이상 상승한 날 이후의 움직임에 대해 찾아보았다

06년도부터 오늘날까지 코스피 종가기준 3.5% 이상 상승한 날을 찾아보았다

```{r read data}
kospi_data <- read.csv("../data/kospi.csv",
                       stringsAsFactors = T,
                       col.names = c("date","price","rate"))
str(kospi_data)


```

## 2. 3.5% 이상이었던 날들
###그리고 그다음날 등락률

```{r pressure, echo=FALSE}
high_rate <- kospi_data[which(
  kospi_data[,3] >= 3.5),]
kable(high_rate)

high1d <- kospi_data[which(kospi_data[,3]>=3.5)+1,] %>%
  na.omit()
high2d <- kospi_data[which(kospi_data[,3]>=3.5)+2,] %>%
  na.omit()
high3d <- kospi_data[which(kospi_data[,3]>=3.5)+3,] %>%
  na.omit()
high4d <- kospi_data[which(kospi_data[,3]>=3.5)+4,] %>%
  na.omit()
high5d <- kospi_data[which(kospi_data[,3]>=3.5)+5,] %>%
  na.omit()

table(mean(high1d$rate),
mean(high2d$rate),
mean(high3d$rate),
mean(high4d$rate),
mean(high5d$rate))

dt2 <- na.omit(dt2)

d_up <- count(dt[which(dt2$> 0),])
d_down <- count(dt[which(dt2$< 0),])
data.frame( "상승" = c(15,15/26),
            "하락" = c(11,11/25))
  
```

## 3. 연도별 차트


```{r }




```

