---
title: "ggmap을 사용한 시각화"
author: "20143311 김희수"
date: sys.date()
output: html_document
---

```{r package setup, include=FALSE}
key <- "AIzaSyAUiBzhHBW7hohoq-CHsEBF13iaRUjJ-X8"
library('ggmap')
register_google(key=key)

```

## Get Coord & Visualization (Bus Stop)

```{r Get Coord & Visualization 2, echo=FALSE}
busstop <- read.csv("../data/bus_stop_gis.csv",
                    col.names = c("id","name","lon","lat"))
busstop <- busstop[ ,c(2,3,4)]
str(busstop)

cc1 <- get_map('Chuncheon',zoom = 14, maptype = 'roadmap')
cc1.map <- ggmap(cc1) +
  geom_point(data = busstop,
             mapping = aes(x=lon,y =lat),
             color = "blue",
             size = 1)
cc1.map

```

## Get Coord & Visualization (Tourists Sites)

```{r Get Coord & Visualization 2, echo=FALSE}
#get coord
T_sites <- read.csv()
T_sites <- T_sites[,]
str(T_sites)

#visualization
cc2 <- get_map('Chuncheon',zoom = 14, maptype = 'roadmap')
cc2.map <- ggmap(cc2) +
  geom_point(data = T_sites,
             mapping = aes(x=lon, y = lat),
             color = "red",
             size = 1)
cc2.map
```

## Set Path & Labeling

```{r}
##위경도 세팅
locationInfo <- data.frame(
    Name = c("강남", "양재", "양재시민의숲", "청계산입구", "판교", "정자"), 
    lon = c(127.028046, 127.035140, 127.038451, 127.054769, 127.111172, 127.108367), 
    lat = c(37.497001, 37.483368, 37.469655, 37.448196, 37.394786, 37.366777))
p3 <- get_googlemap("gwacheon", zoom = 11) %>% ggmap
p3 <- p3 + geom_point(data = locationInfo, aes(x = lon, y = lat)) +
  geom_text(data = locationInfo, aes(label = Name), size = 4, hjust = 1.2, fontface = "bold")
p3
p3 + geom_path(data = locationInfo, aes(x = lon, y = lat), color = "blue", alpha = .5, lwd = 1)


```

